--- #YAML:1.0
name:               Scalar-List-Utils
version:            1.23
abstract:           Common Scalar and List utility subroutines
author:
    - Graham Barr <gbarr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
resources:
    repository:  http://github.com/gbarr/Scalar-List-Utils
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
